name: Build Samples

on:
  push:
    branches: [ main ]
    paths: ['samples/poster.tex', 'samples/slides.tex']

jobs:
  build_latex:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v1
      - name: Compile LaTeX poster
        uses: xu-cheng/latex-action@master
        with:
          root_file: samples/poster.tex
      - name: Compile LaTeX slides
        uses: xu-cheng/latex-action@master
        with:
          root_file: samples/slides.tex
      - name: Upload artifacts
        uses: actions/upload-artifact@master
        with:
          # Artifact name
          name: samples
          # Directory containing files to upload
          path: samples
        if: success()
