name: Build Samples

on:
  push:
    branches: [ master ]
    paths: ['samples/paper.tex', 'samples/slides.tex']

jobs:
  build_latex:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v1
      - name: Compile LaTeX paper
        uses: xu-cheng/latex-action@master
        with:
          root_file: samples/paper.tex
      - name: Upload paper artifact
        uses: actions/upload-artifact@v1.0.0
        with:
          # Artifact name
          name: paper.pdf
          # Directory containing files to upload
          path: samples/
      - name: Compile LaTeX slides
        uses: xu-cheng/latex-action@master
        with:
          root_file: samples/slides.tex
      - name: Upload paper artifact
        uses: actions/upload-artifact@v1.0.0
        with:
          # Artifact name
          name: slides.pdf
          # Directory containing files to upload
          path: samples/
